/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AnalyzeImport } from './routes/analyze'
import { Route as ColumnImport } from './routes/$column'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AnalyzeRoute = AnalyzeImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRoute,
} as any)

const ColumnRoute = ColumnImport.update({
  id: '/$column',
  path: '/$column',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$column': {
      id: '/$column'
      path: '/$column'
      fullPath: '/$column'
      preLoaderRoute: typeof ColumnImport
      parentRoute: typeof rootRoute
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$column': typeof ColumnRoute
  '/analyze': typeof AnalyzeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$column': typeof ColumnRoute
  '/analyze': typeof AnalyzeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$column': typeof ColumnRoute
  '/analyze': typeof AnalyzeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$column' | '/analyze'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$column' | '/analyze'
  id: '__root__' | '/' | '/$column' | '/analyze'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColumnRoute: typeof ColumnRoute
  AnalyzeRoute: typeof AnalyzeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColumnRoute: ColumnRoute,
  AnalyzeRoute: AnalyzeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$column",
        "/analyze"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$column": {
      "filePath": "$column.tsx"
    },
    "/analyze": {
      "filePath": "analyze.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
