/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SummaryImport } from './routes/summary'
import { Route as IndexImport } from './routes/index'
import { Route as ColumnImport } from './routes/$column'

// Create/Update Routes

const SummaryRoute = SummaryImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ColumnRoute = ColumnImport.update({
  id: '/$column',
  path: '/$column',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryImport
      parentRoute: typeof rootRoute
    }
    '/$column': {
      id: '/$column'
      path: '/$column'
      fullPath: '/$column'
      preLoaderRoute: typeof ColumnImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/summary': typeof SummaryRoute
  '/$column': typeof ColumnRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/summary': typeof SummaryRoute
  '/$column': typeof ColumnRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/summary': typeof SummaryRoute
  '/$column': typeof ColumnRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/summary' | '/$column'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/summary' | '/$column'
  id: '__root__' | '/' | '/summary' | '/$column'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SummaryRoute: typeof SummaryRoute
  ColumnRoute: typeof ColumnRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SummaryRoute: SummaryRoute,
  ColumnRoute: ColumnRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/summary",
        "/$column"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/summary": {
      "filePath": "summary.tsx"
    },
    "/$column": {
      "filePath": "$column.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
